### ISSUE TITLE
Prepare some integration tests for generator-camel-project

### ISSUE THREAD

**Issue by tsedmik** [camel-tooling/generator-camel-project#41]
My first thoughts about it. @djelinek can you please look at it?
 ![generator-camel-project](https://user-images.githubusercontent.com/5408450/50968353-11c49500-14db-11e9-945d-faa5c6e080e1.png)

**Comment by djelinek** [comment]
@tsedmik, @bfitzpat , Hi guys, here is new repository, where will be placed all tests - https://github.com/djelinek/generator-camel-project-tests, at this time there is ready first test scenario (Create a new project with prompts with using default generator values)

**Comment by bfitzpat** [comment]
I get some errors when I run it locally. I think it's looking for "yo" locally for some reason (I have yo installed and the generator)
``
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.123 s<<< FAILURE! - in Can be camel project create with prompts?
[ERROR] Using default values(Can be camel project create with prompts?)  Time elapsed: 0.104 s  <<< ERROR!
java.io.IOException: Cannot run program "yo" (in directory "C:\Users\brianf\Documents\GitHub\generator-camel-project-tests\target\generator-camel-project\myproject"): CreateProcess error=2, The system cannot find the file specified
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified

[INFO]
[INFO] Results:
[INFO]
[ERROR] Errors:
[ERROR]   Cannot run program "yo" (in directory "C:\Users\brianf\Documents\GitHub\generator-camel-project-tests\target\generator-camel-project\myproject"): CreateProcess error=2, The system cannot find the file specified
[INFO]
[ERROR] Tests run: 1, Failures: 0, Errors: 1, Skipped: 0
``

**Comment by djelinek** [comment]
Could you please run "yo camel-project" inside "C:\Users\brianf\Documents\GitHub\generator-camel-project-tests\target\generator-camel-project\myproject" ? or it is working fine if you execute it manually ?

**Comment by bfitzpat** [comment]
I could execute it manually inside the target directory - see https://gist.github.com/bfitzpat/01178521246f612aeecce564a046012c

**Comment by djelinek** [comment]
I don't understand why is used path "C:\Users\brianf\Documents\GitHub\generator-camel-project-tests\target\generator-camel-project\myproject" instead of "brianf@brianf-work MINGW64 ~/Documents/GitHub/generator-camel-project-tests/target/generator-camel-project/myproject (master)" where 'yo camel-project' obviously works

**Comment by bfitzpat** [comment]
I'm guessing it's a Windows thing. I'm setting up a Linux box next week and will try it there to see if I get a similar result.

**Comment by djelinek** [comment]
Ok, thank you very much.

**Comment by bfitzpat** [comment]
Found a fix for the windows issue - https://github.com/djelinek/generator-camel-project-tests/pull/1

**Comment by bfitzpat** [comment]
https://gist.github.com/bfitzpat/05ecadf3cf4402741e9b1e58960fb1a4

**Comment by djelinek** [comment]
Nice, thank you very much for your help. I am happy that tests are otherwise working...
I will merge your PR as soon as possible. FYI I have already prepared a few next tests and it looks good. 🙂

**Comment by bfitzpat** [comment]
Awesome. The Cucumber framework seems VERY interesting as an implementation of the user stories approach, so I'm very curious to see how you add other tests! Glad I could help!

**Comment by tsedmik** [comment]
Closing - we choose different approach for project creation --> Project Initializer
